-- 1) intervals (fixed, prepopulate once)
CREATE TABLE intervals_AM (
  interval_id   NUMBER(3) PRIMARY KEY,         -- 1..6
  label         VARCHAR2(50) NOT NULL,         -- "08:00-10:00"
  start_time    VARCHAR2(5)  NOT NULL,         -- store as '08:00'
  end_time      VARCHAR2(5)  NOT NULL
);

-- 2) employees
CREATE TABLE employees_AM (
  employee_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR2(200) NOT NULL,
  email         VARCHAR2(320) UNIQUE,
  password      VARCHAR2(400) NOT NULL,
  phone_number  VARCHAR2(20),
  role          VARCHAR2(20) NOT NULL,
  CONSTRAINT chk_employee_role CHECK (role IN ('Technician','TeamLeader'))
);

-- 3) work_orders  (renamed from tasks)
CREATE TABLE work_orders_AM (
  work_order_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title                    VARCHAR2(400) NOT NULL,
  description              CLOB,
  customer_name            VARCHAR2(200) NOT NULL,     -- Customer name*
  customer_mobile          VARCHAR2(30)  NOT NULL,     -- Customer mobile number*
  customer_email           VARCHAR2(320),
  customer_address         CLOB,
  proposed_scheduling_date DATE         NOT NULL,      -- Proposed scheduling date*
  created_at               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
  created_by               NUMBER NOT NULL,             -- references employees (team leader)
  status                   VARCHAR2(30) DEFAULT 'Not Assigned' NOT NULL,
  CONSTRAINT fk_wo_created_by FOREIGN KEY (created_by)
    REFERENCES employees (employee_id)
);

-- 4) work_order_assignments  (renamed & updated)
CREATE TABLE work_order_assignments_AM (
  assignment_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_order_id   NUMBER NOT NULL,
  employee_id     NUMBER NOT NULL,
  work_date       DATE   NOT NULL,
  interval_id     NUMBER(3) NOT NULL,
  assigned_at     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
  assigned_by     NUMBER NOT NULL,               -- which team leader assigned the task
  CONSTRAINT fk_woa_work_order FOREIGN KEY (work_order_id)
    REFERENCES work_orders (work_order_id) ON DELETE CASCADE,
  CONSTRAINT fk_woa_employee FOREIGN KEY (employee_id)
    REFERENCES employees (employee_id) ON DELETE CASCADE,
  CONSTRAINT fk_woa_interval FOREIGN KEY (interval_id)
    REFERENCES intervals (interval_id),
  CONSTRAINT fk_woa_assigned_by FOREIGN KEY (assigned_by)
    REFERENCES employees (employee_id),
  CONSTRAINT uq_emp_date_interval UNIQUE (employee_id, work_date, interval_id),
  CONSTRAINT chk_woa_status CHECK (status IN ('Assigned','InProgress','Completed','Cancelled','Pending'))
);

-- Helpful indexes for common query shapes
CREATE INDEX ix_woa_emp_date ON work_order_assignments (employee_id, work_date);
CREATE INDEX ix_woa_date_interval ON work_order_assignments (work_date, interval_id);

-- Example: prepopulate intervals (6 fixed intervals)
INSERT INTO intervals (interval_id, label, start_time, end_time) VALUES (1, '08:00-10:00', '08:00', '10:00');
INSERT INTO intervals (interval_id, label, start_time, end_time) VALUES (2, '10:00-12:00', '10:00', '12:00');
INSERT INTO intervals (interval_id, label, start_time, end_time) VALUES (3, '12:00-14:00', '12:00', '14:00');
INSERT INTO intervals (interval_id, label, start_time, end_time) VALUES (4, '14:00-16:00', '14:00', '16:00');
INSERT INTO intervals (interval_id, label, start_time, end_time) VALUES (5, '16:00-18:00', '16:00', '18:00');
INSERT INTO intervals (interval_id, label, start_time, end_time) VALUES (6, '18:00-20:00', '18:00', '20:00');

COMMIT;
